### ISSUE TITLE
Error in Running the containers with mounted linstor volume

### ISSUE THREAD

**Issue by LochanaMendis** [LINBIT/linstor-docker-volume#3]
**### Error in trying to run the container with the attached volume**
root@node3:/home/node3# docker volume ls
DRIVER              VOLUME NAME
linstor             drbd-volume

root@node3:/home/node3# docker run -it --rm --name=cont  -v drbd-volume:/data --volume-driver=linstor busybox sh
docker: Error response from daemon: create drbd-volume: found reference to volume 'drbd-volume' in driver 'linstor', but got an error while checking the driver: error while checking if volume "drbd-volume" exists in driver "linstor": Post http://%2Frun%2Fdocker%2Fplugins%2Flinstor.sock/VolumeDriver.Get: EOF: volume name must be unique.

root@node1:/home/node1# linstor resource-definition list
╭───────────────────────────────────────────────╮
┊ ResourceName   ┊ Port ┊ ResourceGroup ┊ State ┊
╞═══════════════════════════════════════════════╡
┊ docker-storage ┊ 7000 ┊ DfltRscGrp    ┊ ok    ┊
┊ drbd-volume    ┊ 7001 ┊ DfltRscGrp    ┊ ok    ┊
╰───────────────────────────────────────────────╯
root@node1:/home/node1# linstor resource list
╭───────────────────────────────────────────────────╮
┊ ResourceName   ┊ Node  ┊ Port ┊ Usage  ┊    State ┊
╞═══════════════════════════════════════════════════╡
┊ docker-storage ┊ node1 ┊ 7000 ┊ Unused ┊ Diskless ┊
┊ docker-storage ┊ node2 ┊ 7000 ┊ Unused ┊ UpToDate ┊
┊ docker-storage ┊ node3 ┊ 7000 ┊ Unused ┊ UpToDate ┊
┊ drbd-volume    ┊ node2 ┊ 7001 ┊ Unused ┊ UpToDate ┊
┊ drbd-volume    ┊ node3 ┊ 7001 ┊ Unused ┊ UpToDate ┊
╰───────────────────────────────────────────────────╯

**Comment by rck** [comment]
Please try using https://github.com/beornf/linstor-docker-volume . The one from beornf should have become the official plugin some time ago, I just was too busy with other things. This Python one is basically EoL.
